-- Product Q&A questions submitted from the storefront
CREATE TABLE IF NOT EXISTS public.questions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id uuid NOT NULL REFERENCES public.products(product_id) ON DELETE CASCADE,
  user_id uuid NULL REFERENCES auth.users(id) ON DELETE SET NULL,
  name text NOT NULL,
  email text NOT NULL,
  question text NOT NULL,
  status text NOT NULL DEFAULT 'pending'
    CHECK (status = ANY (ARRAY['pending'::text, 'answered'::text, 'archived'::text])),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS questions_product_id_idx ON public.questions (product_id);
CREATE INDEX IF NOT EXISTS questions_status_idx ON public.questions (status);
CREATE INDEX IF NOT EXISTS questions_created_at_idx ON public.questions (created_at DESC);

ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can submit questions"
ON public.questions
FOR INSERT
TO anon, authenticated
WITH CHECK (true);

CREATE POLICY "Admins manage questions"
ON public.questions
FOR ALL
TO authenticated
USING (is_admin())
WITH CHECK (is_admin());
